---
title: "Exercise 5 - Explainable"
author: "Samuel Dion"
date: '2022-05-30'
output: 
  pdf_document: 
    latex_engine: xelatex
    keep_tex: yes
  github_document: default
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F)

```

# Summary

**Questions**

-   What is complex contagion and how it's different from simple
    contagion (refer to reading - Centola)

-   What does complex contagion mean for diffusion of behaviors in
    organization

-   How can we use the threshold models to better manage:

    -   Prosocial behavior in organization

    -   Learning

    -   Toxic or unproductive behaviors

------------------------------------------------------------------------

## **Difference between simple contagion and complex**

If we take the example of spreading fake news, simple contagion is the
hypothesis that you only need one person in connection with you to
assume that you would be "infected" by it. However, in many cases, you
actually need to be exposed to the virus (in this case the fake news) to
actually be "infected". This idea of exposition in the network is called
complex contagion. In complex contagion, there is a threshold to reach
in order to become infected and corresponds to the ratio of connections
that are infected over the total number of connections. In simple
contagion, you only need one connection to be infected so that means a
threshold of 0%.

Furthermore, complex contagion has a different behavior from simple
contagion when talking about connections. Indeed, the more connections
there are in a network, the more the virus spreads when analyzing a
simple contagion model. On the contrary, for a complex contagion model,
the more connections, the less susceptible a network can be infected.
That is because, the initial virus can't infect people with many
connections that aren't affected. This is similar to peer pressure where
if the majority is well connected and never go out for drinks on
Thursday, it would be hard for a single individual to convince them to
start adopting the Thursday drinks.

## Diffusion of behaviors in an organization

For an organization, this means that a very disconnected network with
subgroups will have very poor diffusion of behaviors. On the other end
of the spectrum, a very dense connected network will also have poor
diffusion of behaviors. That is because, each member will have
difficulty to be infected because of all his other connections that are
not. Depending on the threshold to be infected, this will mean that it
would be very hard for someone to adopt new behaviors. For an
organization, it is then best to have just the right amount of
connections to spread and adopt new complex ideas. This means to have
connected subgroups with enough bridge between them to spread behaviors.
This is an equilibrium between bonds within groups and bridges between
groups. You would also need to be vigilant for the transmission of bad
behaviors.

## How to use the threshold model to manage better

Depending on the kind of behaviors that we want to transmit or not, it
is first very important to analyze and try to quantify the threshold
numbers first. When we are talking about actual viruses, the
transmission rate is very important to quantify first in order to remove
connections or allow for more connections (think about COVID rules and
quarantine measures). The same applies for behaviors and learning where
someone that displays good behaviors and work ethic should be well
connected in the organization whereas someone with bad behaviors or
toxic behaviors needs to be disconnected with gullible individuals and
connected back to those that are pro-social behaviors. In a sense, we
want to manipulate the exposure of good/bad tendencies in the
organization to ensure that we are transmitting the right behaviors. In
terms of learning, someone will need a good exposure to learn and in a
sense means that it should be exposed to people with certain skills so
that he can acquire knowledge.
